//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimurNigmatov422_RaNubiWPF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public int Pet_Id { get; set; }
        public string Text { get; set; }
        public int InfoCreator_Id { get; set; }
        public byte[] ImageBytes { get; set; }
    
        public virtual Pet Pet { get; set; }
        public virtual Users Users { get; set; }
    }
}
